# Generated by Django 3.2.13 on 2022-06-29 22:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RailDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=5)),
                ('track', models.CharField(max_length=5)),
                ('km', models.FloatField()),
                ('created', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Circulacion', 'CIRCULATION'), ('Apartado', 'SECONDARY'), ('Talleres', 'GARAGE')], max_length=20)),
                ('direction', models.CharField(choices=[('A', 'ASCENDANT'), ('D', 'FALLING'), ('AD', 'ASC_N_FALL')], max_length=20)),
                ('rail_typology_code', models.CharField(choices=[('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('P1', 'P1'), ('P2', 'P2'), ('BA-PL', 'BAPL'), ('PL-BA', 'PLBA'), ('PN-DS', 'PNDS'), ('DS-PN', 'DSPN'), ('BA', 'BA'), ('PL', 'PL'), ('DS', 'DS'), ('ES', 'ES'), ('PN', 'PN')], max_length=20)),
                ('armament', models.CharField(choices=[('Madera', 'WOOD'), ('Monoblock', 'MONOBLOCK'), ('Stedef', 'STEDEF'), ('S.Directa', 'DIRECT_FASTENING')], max_length=20)),
                ('fastening', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('rail_typology', models.CharField(choices=[('Placa', 'PLAQUE'), ('Balasto', 'BALLAST')], max_length=20)),
                ('circulation_speed', models.CharField(max_length=5)),
                ('technical_location_code', models.CharField(max_length=20)),
                ('inter_station_code', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'ordering': ['line', 'track', 'km'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tracing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=5)),
                ('track', models.CharField(max_length=5)),
                ('km', models.FloatField()),
                ('created', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20)),
                ('geometry_type', models.CharField(choices=[('Recta', 'STRAIGHT'), ('Circular', 'CIRCULAR'), ('Clotoide', 'CLOTHOID')], max_length=20)),
                ('radius', models.CharField(max_length=20)),
                ('arrow', models.CharField(max_length=20)),
                ('theo_width', models.CharField(max_length=20)),
                ('radius_width', models.CharField(max_length=20)),
                ('use_width', models.CharField(max_length=20)),
                ('project_cant', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['line', 'track', 'km'],
                'abstract': False,
            },
        ),
    ]
